//*> API CALLING CONSTANTS
export const GET_API = 'GET';
export const POST_API = 'POST';
export const PUT_API = 'PUT';
export const DELETE_API = 'DELETE';
export const UPDATE_API = 'PUT';
export const PATCH_API = 'PATCH';


//*> USER CONSTATNS
export const LOGIN_USER_REQUESTED = "LOGIN_USER_REQUESTED"
export const LOGIN_USER_SUCCESS = "LOGIN_USERS_SUCCESS"
export const LOGIN_USERS_FAILED = "LOGIN_USERS_FAILED"

export const SIGNUP_USER_REQUESTED = "SIGNUP_USER_REQUESTED"
export const SIGNUP_USER_SUCCESS = "SIGNUP_USER_SUCCESS"
export const SIGNUP_USER_FAILED = "SIGNUP_USER_FAILED"

export const FORGOT_PASSWORD_REQUESTED = "FORGOT_PASSWORD_REQUESTED"
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS"
export const FORGOT_PASSWORD_FAILED = "FORGOT_PASSWORD_FAILED"

export const VERIFY_OTP_REQUESTED = "VERIFY_OTP_REQUESTED"
export const VERIFY_OTP_SUCCESS = "VERIFY_OTP_SUCCESS"
export const VERIFY_OTP_FAILED = "VERIFY_OTP_FAILED"

export const RESET_PASSWORD_REQUESTED = "RESET_PASSWORD_REQUESTED"
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS"
export const RESET_PASSWORD_FAILED = "RESET_PASSWORD_FAILED"

//*>HelpCenter
export const GET_HELP_CENTER_DETAILS_REQUESTED = 'GET_HELP_CENTER_DETAILS_REQUESTED';
export const GET_HELP_CENTER_DETAILS_SUCCESS = 'GET_HELP_CENTER_DETAILS_SUCCESS';
export const GET_HELP_CENTER_DETAILS_FAILED = 'GET_HELP_CENTER_DETAILS_FAILED';


//*>APP LOADER
export const START_SPINNER = "START_SPINNER"
export const STOP_SPINNER = "STOP_SPINNER"

//*> ERROR MODAL
export const SHOW_ERROR_MODAL = "SHOW_ERROR_MODAL"  
export const HIDE_ERROR_MODAL = "HIDE_ERROR_MODAL"

//*> EDIT PROFILE
export const GET_EDIT_PROFILE_REQUESTED = "GET_EDIT_PROFILE_REQUESTED"
export const GET_EDIT_PROFILE_SUCCESS = "GET_EDIT_PROFILE_SUCCESS"
export const GET_EDIT_PROFILE_FAILED = "GET_EDIT_PROFILE_FAILED"

export const CHANGE_PASSWORD_REQUESTED = "CHANGE_PASSWORD_REQUESTED"
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS"
export const CHANGE_PASSWORD_FAILED = "CHANGE_PASSWORD_FAILED"

export const GET_OTP_REQUESTED = "GET_OTP_REQUESTED"
export const GET_OTP_SUCCESS = "GET_OTP_SUCCESS"
export const GET_OTP_FAILED = "GET_OTP_FAILED"

export const UPDATE_ACCOUNT_REQUESTED = "UPDATE_ACCOUNT_REQUESTED"
export const UPDATE_ACCOUNT_SUCCESS = "UPDATE_ACCOUNT_SUCCESS"
export const UPDATE_ACCOUNT_FAILED = "UPDATE_ACCOUNT_FAILED"